### ISSUE TITLE
Unable to run with multiple entities in NamespaceConfig

### ISSUE THREAD

**Issue by Ruud2000** [Azure/azure-event-hubs-emulator-installer#17]
**Describe the bug**
Trying to get the Event Hubs Emulator up and running locally with multiple entities. I use the default config from this file as starting point: https://github.com/Azure/azure-event-hubs-emulator-installer/blob/main/EventHub-Emulator/Config/Config.json

And add 1 extra entity **eh2** to the list of entities:
```json
{
    "UserConfig": {
        "NamespaceConfig": [
        {
            "Type": "EventHub",
            "Name": "emulatorNs1",
            "Entities": [
            {
                "Name": "eh1",
                "PartitionCount": "2",
                "ConsumerGroups": [
                {
                    "Name": "cg1"
                },
                {
                    "Name": "cg2"
                }
                ]
            },
            {
                "Name": "eh2",
                "PartitionCount": "2",
                "ConsumerGroups": [
                {
                    "Name": "cg3"
                },
                {
                    "Name": "cg4"
                }
                ]
            }
            ]
        }
        ], 
        "LoggingConfig": {
            "Type": "File"
        }
    }
}
```

I use the .NET code example: https://github.com/Azure/azure-event-hubs-emulator-installer/blob/main/Sample-Code-Snippets/.NET/EventHubs-Emulator-Demo/EventHubs-Emulator-Demo/Program.cs

And change on line 13 the `eventHubName` variable to `eh2`. This results in the following exception when creating the batch on line 38:

```
Azure.Messaging.EventHubs.EventHubsException
  HResult=0x80131500
  Message=The messaging entity 'sb://emulatorns1.eventhubs.emulator.net/eh2' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:2ec60e52e2a946eebebe2fc026a24abb_G0, SystemTracker:gateway1, Timestamp:2024-06-10T14:54:39
  Source=Azure.Messaging.EventHubs
  StackTrace:
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.<CreateBatchAsync>d__42.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Messaging.EventHubs.Producer.EventHubProducerClient.<CreateBatchAsync>d__54.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Messaging.EventHubs.Producer.EventHubProducerClient.<CreateBatchAsync>d__53.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Program.<Send>d__4.MoveNext() in C:\Users\[redacted]\source\repos\azure-event-hubs-emulator-installer\Sample-Code-Snippets\.NET\EventHubs-Emulator-Demo\EventHubs-Emulator-Demo\Program.cs:line 38
   at Program.<Main>d__3.MoveNext() in C:\Users\[redacted]\source\repos\azure-event-hubs-emulator-installer\Sample-Code-Snippets\.NET\EventHubs-Emulator-Demo\EventHubs-Emulator-Demo\Program.cs:line 18

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
AmqpException: The messaging entity 'sb://emulatorns1.eventhubs.emulator.net/eh2' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:2ec60e52e2a946eebebe2fc026a24abb_G0, SystemTracker:gateway1, Timestamp:2024-06-10T14:54:39
```

Note the namespace is now **emulatorns1** while this is **localhost** in the connection string and also the fully qualified namespace of the EventHubProducerClient as shown in the screenshot:

![image](https://github.com/Azure/azure-event-hubs-emulator-installer/assets/41336158/6e6b3fce-2120-4d4a-b32d-f0d69ac2d8bd)

I would expect the EventHubProducerClient could simply create a batch on the **eh2** entity.

**To Reproduce**
See above steps.

Used the following default docker compose file:
```docker
name: microsoft-azure-eventhubs
services:
  emulator:
    container_name: "eventhubs-emulator"
    image: "mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest"
    volumes:
      - ./Config.json:/Config.json
    ports:
      - "5672:5672"
    environment:
      BLOB_SERVER: azurite
      METADATA_SERVER: azurite
      ACCEPT_EULA: "Y"
    depends_on:
      - azurite
    networks:
      eh-emulator:
        aliases:
          - "eventhubs-emulator"
  azurite:
    container_name: "azurite"
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      eh-emulator:
        aliases:
          - "azurite"
networks:
  eh-emulator:
```

I start the container in `wsl` using the following commands in order:
`docker compose -f docker-compose-default.yml down`
`docker compose -f docker-compose-default.yml up -d`

**Expected behavior**
Same behavior for **eh2** as for **eh1**

**Desktop:**
Output `wsl -v`
```
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3593
```

Output `docker version`:
```
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Arguments && Environment variables to start Emulator:**
- ACCEPT_EULA: Y
- CONFIG_PATH: ./Config.json:/Config.json

**Emulator Launch Method:**
 - Direct Docker compose

**Comment by krishankumar95** [comment]
@Ruud2000  CONFIG_PATH env variable seems to have a gap.

The bind mount on the container side (RHS) needs to be ```/Eventhubs_Emulator/ConfigFiles/Config.json``` and cannot be changed.
So the correct value will be ```"./Config.json:/Eventhubs_Emulator/ConfigFiles/Config.json"``` given the Config.json is present in the same directory as the compose file (Or any other path relative to docker compose can be provided in LHS) 


Emulator also logs the user configuration it is launching which in console: 

```
docker logs -f --tail 100 eventhubs-emulator

info: a.a.aap[0]
      Emulator Service is Launching On Platform:CBL-Mariner/Linux,X64
info: a.a.aap[0]
      Instantiating service components
info: a.a.aap[0]
      Creating namespace, entities and consumer groups
info: a.a.aaW[0]
      Emulator is launching with config : {"LoggingConfig":{"Type":"File"},"NamespaceConfig":[{"Type":"EventHub","Name":"emulatorns1","Entities":[{"Name":"eh1","PartitionCount":2,"ConsumerGroups":[{"Name":"cg1"},{"Name":"$default"}]},{"Name":"eh2","PartitionCount":2,"ConsumerGroups":[{"Name":"cg2"},{"Name":"$default"}]}]}]}
info: a.a.aap[0]
      Emulator Service is Successfully Up! ; Use connection string : "Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
```

**Comment by Ruud2000** [comment]
@krishankumar95 great! That did the trick, I have it up and running now.
